### ISSUE TITLE
Create product page

### ISSUE THREAD

**Issue by arslanastral** [chingu-voyages/v41-bears-team-32#68]
**__Task Description__**
Create product page. Product page should clearly show product name, description, price and other relevant information.

**__Technical Considerations__**
~~Product page should use new app directory of Next.js 13 for simplified data fetching.~~
Never mind, it's not ready yet for dependencies of this project.

**__Resource__**
https://beta.nextjs.org/docs/routing/defining-routes

**Comment by genelorenzSarmiento0408** [comment]
Next.js 13 `app` dir is not yet been supported by tRPC (the backend)

**Comment by genelorenzSarmiento0408** [comment]
I think this issue has been resolved, closing it
